<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class HistoriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //履歴データ
        DB::table('histories')->insert([
            [
                'user_id' => 1,
                'title' => '最大文字数まで入れてみたタイトルなのです',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => NULL,
                'task4' => NULL,
                'task5' => NULL,
                'task6' => NULL,
                'task7' => NULL,
                'task8' => NULL,
                'task9' => NULL,
                'started_at' => date('2019-08-03 08:05:01'),
                'finished_at' => date('2019-08-03 10:25:39'),
                'completion' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => 'ふたつめのタイトルなの',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => 'よっつめのタスクなの',
                'task4' => NULL,
                'task5' => NULL,
                'task6' => NULL,
                'task7' => NULL,
                'task8' => NULL,
                'task9' => NULL,
                'started_at' => date('2019-08-04 07:05:01'),
                'finished_at' => date('2019-08-04 11:36:49'),
                'completion' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => 'みっつめ！',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => 'よっつめのタスクなの',
                'task4' => 'いつつめのタスクなの',
                'task5' => 'むっつめのタスクなの',
                'task6' => 'ななつめのタスクなの',
                'task7' => 'やっつめのタスクなの',
                'task8' => 'ここのつめのタスクなの',
                'task9' => 'さいごのタスクなの',
                'started_at' => date('2019-08-06 08:15:51'),
                'finished_at' => date('2019-08-06 09:06:45'),
                'completion' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => '日付またぎパターン',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => 'よっつめのタスクなの',
                'task4' => 'いつつめのタスクなの',
                'task5' => 'むっつめのタスクなの',
                'task6' => 'ななつめのタスクなの',
                'task7' => 'やっつめのタスクなの',
                'task8' => NULL,
                'task9' => NULL,
                'started_at' => date('2019-08-12 22:15:51'),
                'finished_at' => date('2019-08-13 01:06:45'),
                'completion' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => 'たいとるー',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => 'よっつめのタスクなの',
                'task4' => 'いつつめのタスクなの',
                'task5' => 'むっつめのタスクなの',
                'task6' => 'ななつめのタスクなの',
                'task7' => 'やっつめのタスクなの',
                'task8' => 'ここのつめのタスクなの',
                'task9' => 'さいごのタスクなの',
                'started_at' => date('2019-08-13 08:45:51'),
                'finished_at' => date('2019-08-13 09:56:45'),
                'completion' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => 'tesutonanoyo',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => 'よっつめのタスクなの',
                'task4' => 'いつつめのタスクなの',
                'task5' => 'むっつめのタスクなの',
                'task6' => NULL,
                'task7' => NULL,
                'task8' => NULL,
                'task9' => NULL,
                'started_at' => date('2019-08-14 08:15:51'),
                'finished_at' => date('2019-08-14 09:06:45'),
                'completion' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => 'ふつーのやつ',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => 'よっつめのタスクなの',
                'task4' => 'いつつめのタスクなの',
                'task5' => 'むっつめのタスクなの',
                'task6' => NULL,
                'task7' => NULL,
                'task8' => NULL,
                'task9' => NULL,
                'started_at' => date('2019-08-15 08:15:51'),
                'finished_at' => date('2019-08-15 09:26:45'),
                'completion' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => '瞬殺してるやつ',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => 'よっつめのタスクなの',
                'task4' => 'いつつめのタスクなの',
                'task5' => 'むっつめのタスクなの',
                'task6' => 'ななつめのタスクなの',
                'task7' => 'やっつめのタスクなの',
                'task8' => 'ここのつめのタスクなの',
                'task9' => 'さいごのタスクなの',
                'started_at' => date('2019-08-16 08:15:51'),
                'finished_at' => date('2019-08-16 08:16:10'),
                'completion' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => 'うまいこといかんかったやつ',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => NULL,
                'task4' => NULL,
                'task5' => NULL,
                'task6' => NULL,
                'task7' => NULL,
                'task8' => NULL,
                'task9' => NULL,
                'started_at' => date('2019-08-17 03:15:51'),
                'finished_at' => date('2019-08-17 15:34:45'),
                'completion' => false,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => '最大文字数まで入れてみたタイトルなのです',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => 'よっつめのタスクなの',
                'task4' => NULL,
                'task5' => NULL,
                'task6' => NULL,
                'task7' => NULL,
                'task8' => NULL,
                'task9' => NULL,
                'started_at' => date('2019-08-18 07:15:51'),
                'finished_at' => date('2019-08-18 09:06:45'),
                'completion' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => 'てすとたいとるなの',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめ',
                'task2' => 'みっつめのタスクなの',
                'task3' => 'よっつめのタスクなの',
                'task4' => 'いつつめのタスクなの',
                'task5' => 'むっつめのタスクなの',
                'task6' => 'ななつめのタスクなの',
                'task7' => 'やっつめのタスクなの',
                'task8' => 'ここのつめのタスクなの',
                'task9' => 'さいごのタスクなの',
                'started_at' => date('2019-08-19 08:15:51'),
                'finished_at' => date('2019-08-19 09:00:45'),
                'completion' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'title' => '最新！',
                'task0' => '最大文字数まで入れてみたタスクはこんなの',
                'task1' => 'ふたつめのタスクなの',
                'task2' => 'みっつめのタスクなの',
                'task3' => 'よっつめのタスクなの',
                'task4' => 'いつつめのタスクなの',
                'task5' => 'むっつめのタスクなの',
                'task6' => 'ななつめのタスクなの',
                'task7' => 'やっつめのタスクなの',
                'task8' => 'ここのつめのタスクなの',
                'task9' => 'さいごのタスクなの',
                'started_at' => date('2019-08-20 01:15:51'),
                'finished_at' => date('2019-08-20 03:45:45'),
                'completion' => true,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
